version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: registry.ilyasabdut.loseyourip.com/split-bill-app:latest
    container_name: split-bill-app
    ports:
      - "8501:8501"
    environment:
      - FASTAPI_API_URL=http://api:8000
      - APP_BASE_URL=${APP_BASE_URL:-http://localhost:8501}
      - API_KEY=${API_KEY}
    restart: unless-stopped
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: registry.ilyasabdut.loseyourip.com/split-bill-api:latest
    container_name: split-bill-api
    ports:
      - "8000:8000"
    environment:
      - API_KEY=${API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
      - GEMINI_MODEL_NAME=${GEMINI_MODEL_NAME:-gemini-1.5-flash}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT:-minio:9000}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-minioadmin}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME:-split-bill}
      - MINIO_USE_SSL=${MINIO_USE_SSL:-False}
      - APP_BASE_URL=${APP_BASE_URL:-http://localhost:8000}
    restart: unless-stopped
