version: "3.8"

services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: registry.ilyasabdut.loseyourip.com/bill-splitter-app:latest # CHANGE IMAGE NAME
    container_name: bill-splitter-streamlit-app # CHANGE CONTAINER NAME
    ports:
      - "8501:8501" # Map host port 8501 to container port 8501 (Streamlit default)
    environment:
      - FASTAPI_API_URL=http://fastapi-api:8000 # Internal Docker network name and port
      - APP_BASE_URL=${APP_BASE_URL:-http://localhost:8501} # External URL for share links
      - API_KEY=${API_KEY} # Pass API_KEY to Streamlit
    restart: unless-stopped
    depends_on:
      - fastapi-api # Ensure FastAPI starts before Streamlit

  fastapi-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: registry.ilyasabdut.loseyourip.com/bill-splitter-api:latest # CHANGE IMAGE NAME
    container_name: bill-splitter-fastapi-api # CHANGE CONTAINER NAME
    ports:
      - "8000:8000" # Map host port 8000 to container port 8000 (FastAPI default)
    environment:
      - API_KEY=${API_KEY} # Pass API_KEY to FastAPI
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL_NAME=${GEMINI_MODEL_NAME:-gemma-3-27b-it} # Default if not set
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME:-split-bill}
      - MINIO_USE_SSL=${MINIO_USE_SSL:-False}
      - APP_BASE_URL=${APP_BASE_URL:-http://localhost:8000} # External URL for share links (FastAPI's own links)
    restart: unless-stopped
