version: "3.8"

services:
  split-bill-app:
    image: registry.ilyasabdut.loseyourip.com/split-bill-app:latest
    container_name: split-bill-app
    ports:
      - "8501:8501"
    environment:
      - FASTAPI_API_URL=http://localhost:8000 # Updated to localhost since both are in the same container
      - APP_BASE_URL=${APP_BASE_URL:-http://0.0.0.0:8501}
      - API_KEY=${API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
      - GEMINI_MODEL_NAME=${GEMINI_MODEL_NAME:-gemini-1.5-flash-latest}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT:-minio:9000}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-minioadmin}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME:-split-bill}
      - MINIO_USE_SSL=${MINIO_USE_SSL:-False}
    restart: unless-stopped
