version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: registry.ilyasabdut.loseyourip.com/split-bill-app:latest
    container_name: split-bill-app
    ports:
      - "8501:8501"
    environment:
      - FASTAPI_API_URL=http://api:8000
      - APP_BASE_URL=${APP_BASE_URL:-http://localhost:8501}
      - API_KEY=${API_KEY}
    restart: unless-stopped
    depends_on:
      - api

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    image: registry.ilyasabdut.loseyourip.com/split-bill-api:latest
    container_name: split-bill-api
    ports:
      - "8000:8000"
    environment:
      - API_KEY=${API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}
      - OPENROUTER_MODEL_NAME=${OPENROUTER_MODEL_NAME:-mistralai/mistral-small-3.2-24b-instruct:free}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT:-minio:9000}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-minioadmin}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME:-split-bill}
      - MINIO_USE_SSL=${MINIO_USE_SSL:-False}
      - APP_BASE_URL=${APP_BASE_URL:-http://localhost:8000}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: valkey/valkey:alpine3.23
    container_name: split-bill-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

volumes:
  redis_data:
