name: Build and Deploy Bill Splitter

on:
  push:
    branches:
      - master # Or 'main'

jobs:
  build-and-push-images: # Renamed job for clarity (plural)
    name: Build and Push Bill Splitter Images
    runs-on: self-hosted # Using your self-hosted runner
    environment: master # Assuming secrets are scoped to this environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        # Ensure your self-hosted runner has buildx capabilities.

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: registry.ilyasabdut.loseyourip.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Streamlit App Image
        uses: docker/build-push-action@v5
        with:
          context: . # Root of your repository
          dockerfile: Dockerfile # Dockerfile for Streamlit
          platforms: linux/arm64 # As per your example, adjust if needed
          push: true
          tags: registry.ilyasabdut.loseyourip.com/split-bill-app:latest # IMPORTANT: Use the correct image name for Streamlit
          # Optional: Build caching for self-hosted runners can be more complex.
          # Consider local Docker layer caching on the runner itself if buildx gha cache isn't suitable.

      - name: Build and Push FastAPI API Image
        uses: docker/build-push-action@v5
        with:
          context: . # Root of your repository
          dockerfile: Dockerfile.api # Dockerfile for FastAPI
          platforms: linux/arm64 # As per your example, adjust if needed
          push: true
          tags: registry.ilyasabdut.loseyourip.com/split-bill-api:latest # IMPORTANT: Use the correct image name for FastAPI

  deploy-on-vps: # Renamed job for clarity
    name: Deploy Bill Splitter to VPS
    needs: build-and-push-images # Depends on both images being built and pushed
    runs-on: self-hosted # This runner IS your VPS or has direct docker-compose access to it
    environment: master

    steps:
      - name: Log in to Docker Registry (on deployment runner/VPS)
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login registry.ilyasabdut.loseyourip.com -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

      - name: Deploy Bill Splitter Apps
        run: |
          echo "Deploying Bill Splitter on $(hostname)"
          
          # IMPORTANT: Navigate to the directory on your VPS where 
          # the docker-compose.yml and .env file for split-bill-app are located.
          APP_COMPOSE_DIR="/home/ubuntu/composes/split-bill-app" # ADJUST THIS PATH
          
          if [ ! -d "${APP_COMPOSE_DIR}" ]; then
            echo "ERROR: Deployment directory ${APP_COMPOSE_DIR} does not exist!"
            exit 1
          fi
          cd "${APP_COMPOSE_DIR}"
          echo "Changed directory to $(pwd)"

          echo "Ensuring .env file exists..."
          if [ ! -f .env ]; then
            echo "ERROR: .env file not found in ${APP_COMPOSE_DIR}. Deployment requires this for configurations."
            exit 1
          fi

          echo "Pulling latest images for both services..."
          # Pull both services defined in your docker-compose.yml
          docker compose pull streamlit-app fastapi-api
          
          echo "Restarting containers using docker compose..."
          # This will stop, remove, and recreate containers for both services if images changed.
          docker compose up -d --force-recreate --remove-orphans

          echo "Cleaning up unused Docker images (optional)..."
          docker image prune -af

          echo "Bill Splitter deployment finished!"
        env: # Pass secrets to the script execution environment if needed by docker login itself
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
