# General server settings
[server]
headless = true             # Essential for Docker/headless environments: doesn't try to open a browser window
port = 8501                 # Ensure it listens on the correct port (matching EXPOSE and docker-compose)
address = "0.0.0.0"         # Listen on all available network interfaces inside the container
fileWatcherType = "none"
maxUploadSize = 2

# Browser-related settings
[browser]
gatherUsageStats = false    # Opt-out of sending usage statistics to Streamlit (good for privacy/prod)

# Global settings for app behavior
[global]
showWarningOnDirectExecution = false # This correctly removes the "re-run app" warning
# disableWatchdogWarning = true      # Optional: Set to true if you experience "watchdog" warnings

# Client-side UI settings (optional, but can make it cleaner)
[client]
toolbarMode = "minimal"     # <--- CHANGE THIS TO "minimal"

[ui]
hideTopBar = true